package:
    name:
        propy
    version: 1.0

source:
    git_url: http://protpy.googlecode.com/files/propy-1.0.tar.gz

requirements:
    build:
        - python
        - setuptools
    script: python setup.py install
    run:
        - python

test:
    imports:
        - propy

about:
    home: https://code.google.com/p/protpy/


